### ISSUE TITLE
TODO 

### ISSUE THREAD

**Issue by StefanLocke** [StefanLocke/PlantsVZombies#1]
- [ ] -non grid UI
- [ ] -sun mecanics (sun  on timer + sunflower)
- [ ] -cooldown system on planting
- [ ] -sunflower mecanics 
- [x] -projectile / shooting mecanic
- [x] -damage tetection
- [ ] -create nut entitie
- [ ] -zombie spawn/ mecanics
- [ ] -
- [ ] 
- [x] - [ ] zombie movement with damage
